services:
  clinical-trials:
    build: .
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./release:/app/release
    environment:
      - DISEASE=Familial Hypercholesterolemia
      - YEAR_START=2008
      - YEAR_END=2023
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - PREFECT_API_KEY=${PREFECT_API_KEY}
      - PREFECT_WORKSPACE=${PREFECT_WORKSPACE}
      - LOG_LEVEL=INFO
    ports:
      - "8501:8501" # Optional if you serve a Streamlit app later